global:
  resolve_timeout: 2m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#project-okrs'
    send_resolved: true