version: "3.7"

services:
  app:
    container_name: "taxi-tapi"
    build:
      context: .
      # no postgress available... no environment
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 2112:2112
    networks:
      - taxi
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./framework/src/main/java/com/taxi/framework/metrics/config/prom:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - taxi
  alertmanager:
    image: prom/alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./framework/src/main/java/com/taxi/framework/metrics/config/alert/alert.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - taxi
  grafana:
    image: grafana/grafana
    ports:
      - 3011:3000
    environment:
      - GF_SECURITY_ADMIN_USER=taxi-parham
      - GF_SECURITY_ADMIN_PASSWORD=taxi-parham
    networks:
      - taxi
